name: "VAN CanBus"
description: "Enable the use of CANFAN in Home Assistant core"
version: "1.0.0"
slug: "vanCanBus"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
privileged:
  - NET_ADMIN
options:
  device: "can0"
  bitrate: 500000
schema:
  device: str
  bitrate: int(10000,1000000)

EXPOSE 8000

