name: "VAN CanBus"
description: "Enable the use of CANFAN in Home Assistant core"
version: "1.0.17"
slug: "van_can_bus"
init: false
arch:
  - aarch64
  - amd64
startup: services
host_network: true
privileged:
  - NET_ADMIN
options:
  device: "can0"
  bitrate: 500000
schema:
  device: str
  bitrate: int(10000,1000000)

ports:
  8000/tcp: 8000
